### ISSUE TITLE
How to start the ui project

### ISSUE THREAD

**Issue by 6866** [making/uaa-ui#1]
Why do you want to do proxy, do not directly access uaa

**Comment by making** [comment]
You mean a fully single page which uses implicit flow or resource owner password flow?
I don't think this type of admin application is tied to a **user**(resource owner).  It's for an admin **client**.
 I found there are some technical inconvenience in direct access to UAA as well (CORS, dynamic configuration and so on).

Please take a look latest README. It supports a client login form. This ui now supports multiple clients.
